version: 2

updates:
  # Cargo Crates
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    reviewers:
      - "RShirohara"
    versioning-strategy: increase
    groups:
      lindera:
        patterns:
          - "lindera-*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: CI"
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
    reviewers:
      - "RShirohara"
