[package]
name = "markov-chain-generator-jp-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
lindera = "0.14.0"
markov = "1.1.0"
regex = "1.6.0"
