name: CI (Rust crate)

on:
  pull_request:
    types: [opened, ready_for_review, review_requested]
    paths: ["Cargo.toml", "**.rs", ".github/workflows/ci-rust.yaml"]
  push:
    branches: [main]

permissions:
  checks: write

env:
  RUST_TOOLCHAIN_TARGET: x86_64-unknown-linux-musl

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ env.RUST_TOOLCHAIN_TARGET }}

      - name: Setup dependencies cache
        uses: Swatinem/rust-cache@v2.6.2
        with:
          prefix-key: rust-cache
          shared-key: ${{ hashFiles('./Cargo.toml') }}
          key: ""

      - name: Build
        run: |
          cargo build \
            --all-features \
            --target=${{ env.RUST_TOOLCHAIN_TARGET }}

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ env.RUST_TOOLCHAIN_TARGET }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.6.2
        with:
          prefix-key: rust-cache
          shared-key: ${{ hashFiles('./Cargo.toml') }}
          key: ""

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.6

      - name: Run clippy
        env:
          CARGO_TERM_COLOR: never
          REVIEWDOG_FORMAT: clippy
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWDOG_REPORTER: github-check
        run: |
          cargo clippy \
            -q \
            --all-features \
            --no-deps \
            --target=${{ env.RUST_TOOLCHAIN_TARGET }} \
            --message-format=short 2>&1 \
          | reviewdog \
              -f="${REVIEWDOG_FORMAT}" \
              --name="Lint result (${REVIEWDOG_FORMAT})" \
              --reporter="${REVIEWDOG_REPORTER}" \
