name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    name: Release for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive: tar.gz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Build and Release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          TOOLCHAIN_VERSION: stable
