name: Rust CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    paths:
      - "Cargo.toml"
      - "**.rs"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.workflow }}
      - name: Build
        run: cargo build --release --all-features
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.workflow }}
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: Run clippy
        env:
          CARGO_TERM_COLOR: never
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo clippy --all-features -q --message-format=short 2>&1 |
          reviewdog -f=clippy -reporter=github-check
